import Image from 'next/image';
import { Header } from '@/components/header';
import { QuoteForm, ProductLink } from '@/components/contact';
import { whatsappUrl } from '@/lib/site';

export default function Home() {
  return <>

    <svg className="icon-library" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs>
      <symbol id="i-arrow" viewBox="0 0 24 24"><path d="M5 12h14m-6-6 6 6-6 6"/></symbol>
      <symbol id="i-up-right" viewBox="0 0 24 24"><path d="M6 18 18 6M6 6h12v12"/></symbol>
      <symbol id="i-check" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></symbol>
      <symbol id="i-shield" viewBox="0 0 24 24"><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/></symbol>
      <symbol id="i-truck" viewBox="0 0 24 24"><path d="M3 5h12v12H3zM15 10h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></symbol>
      <symbol id="i-chat" viewBox="0 0 24 24"><path d="M21 11.5a9 9 0 0 1-13.5 7.8L3 21l1.7-4.5A9 9 0 1 1 21 11.5Z"/><path d="M8 8c0 4 4 8 8 8l1-3-3-1-1 1-2-2 1-1-1-3-3 1Z"/></symbol>
      <symbol id="i-clock" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></symbol>
      <symbol id="i-door" viewBox="0 0 24 24"><path d="M4 21V3h16v18M2 21h20M7 21V6h10v15M8 13h8"/></symbol>
      <symbol id="i-pin" viewBox="0 0 24 24"><path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></symbol>
      <symbol id="i-download" viewBox="0 0 24 24"><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></symbol>
    </defs></svg>
    <a className="skip-link" href="#contenido">Saltar al contenido</a>
    <div className="topbar"><div className="site-container topbar-inner"><span>SEGURIDAD INDUSTRIAL. TRANQUILIDAD REAL.</span><span><svg className="icon" aria-hidden="true"><use href="#i-truck"/></svg> Enviamos a todo el país <span className="topbar-divider">/</span> Fabricación nacional</span></div></div>
    <Header />
    <main id="contenido">
      <section className="hero" id="inicio" aria-labelledby="hero-title">
        <div className="hero-photo"><Image src="/images/puerta-emergencia.jpg" alt="Detalle de las puertas de emergencia Montiuk con barrales antipánico" width={1920} height={700} sizes="(max-width: 680px) 100vw, 65vw" priority /><div className="photo-caption"><span className="status-dot"></span> DISEÑADAS PARA PROTEGER</div></div>
        <div className="site-container hero-content">
          <div className="hero-copy"><div className="eyebrow light"><span></span> PUERTAS CORTAFUEGO Y DE EMERGENCIA</div>
            <h1 id="hero-title">La seguridad de<br />tu obra empieza<br />por una <span>buena puerta.</span></h1>
            <p>Protegé a las personas y tu proyecto con puertas certificadas. Te asesoramos para que elijas la solución que tu obra necesita.</p>
            <div className="hero-actions"><a className="button" href={whatsappUrl('Hola, quiero pedir un presupuesto de puertas para mi obra.')} target="_blank" rel="noopener noreferrer"><svg className="icon" aria-hidden="true"><use href="#i-chat"/></svg> Cotizar por WhatsApp <svg className="icon" aria-hidden="true"><use href="#i-up-right"/></svg></a><a className="text-link light-link" href="#soluciones">Explorar soluciones <svg className="icon" aria-hidden="true"><use href="#i-arrow"/></svg></a></div>
            <div className="hero-note"><svg className="icon" aria-hidden="true"><use href="#i-check"/></svg> Atención personalizada <span>·</span> Presupuesto sin cargo</div>
          </div>
        </div>
        <div className="hero-seal"><svg className="icon" aria-hidden="true"><use href="#i-shield"/></svg><div><strong>Homologación INTI</strong><span>FR30 · FR60 · FR90 · FR120</span></div></div>
        <div className="hero-bottom-line"></div>
      </section>
      <section className="certification-banner" aria-labelledby="certification-title">
        <div className="site-container certification-inner">
          <span className="certification-icon"><svg className="icon" aria-hidden="true"><use href="#i-shield"/></svg></span>
          <div><p>PUERTAS CORTAFUEGO HOMOLOGADAS</p><h2 id="certification-title">Homologación INTI <span>— FR30, FR60, FR90 y FR120</span></h2></div>
        </div>
      </section>
      <section className="trust-strip" aria-label="Nuestro respaldo"><div className="site-container trust-grid">
        <div className="trust-item"><svg className="icon" aria-hidden="true"><use href="#i-shield"/></svg><div><strong>Homologación INTI</strong><span>FR30 · FR60 · FR90 · FR120</span></div></div>
        <div className="trust-item"><svg className="icon" aria-hidden="true"><use href="#i-door"/></svg><div><strong>Fabricación nacional</strong><span>Calidad en cada detalle</span></div></div>
        <div className="trust-item"><svg className="icon" aria-hidden="true"><use href="#i-chat"/></svg><div><strong>Asesoramiento técnico</strong><span>Elegí con información clara</span></div></div>
        <div className="trust-item"><svg className="icon" aria-hidden="true"><use href="#i-truck"/></svg><div><strong>Envíos a todo el país</strong><span>Desde Buenos Aires a tu obra</span></div></div>
      </div></section>
      <section className="section solutions" id="soluciones">
        <div className="site-container"><div className="section-heading"><div><div className="eyebrow"><span></span> NUESTRAS SOLUCIONES</div><h2>La puerta correcta.<br />Para cada necesidad.</h2></div><p>Desde una salida de emergencia hasta un proyecto integral. Encontrá lo que necesitás, con el respaldo de especialistas.</p></div>
          <div className="grid grid-cols-1 gap-6 min-[681px]:grid-cols-3 min-[681px]:gap-[13px] min-[901px]:gap-[22px]">
            <article className="product-card"><div className="product-image fire-image"><Image src="/images/puerta-cortafuego.jpg" alt="Modelos Montiuk de puertas cortafuego de una y dos hojas" loading="lazy" width={1500} height={617}/><span className="product-tag"><svg className="icon" aria-hidden="true"><use href="#i-shield"/></svg> HOMOLOGADAS POR EL INTI</span><span className="product-number">01</span></div><div className="product-content"><h3>Puertas cortafuego</h3><p>Ayudan a contener el fuego y proteger las vías de escape. Opciones según la exigencia de tu proyecto.</p><div className="product-specs"><span>FR30 · FR60 · FR90 · FR120</span><span>Simple y doble hoja</span></div><ProductLink product="Puertas cortafuego">Cotizar puertas cortafuego</ProductLink></div></article>
            <article className="product-card"><div className="product-image emergency-image"><Image src="/images/puerta-emergencia.jpg" alt="Puertas para salida de emergencia con barral antipánico" loading="lazy" width={1920} height={700}/><span className="product-tag">APERTURA ANTIPÁNICO</span><span className="product-number">02</span></div><div className="product-content"><h3>Puertas de emergencia</h3><p>Una salida práctica y segura para espacios de alto tránsito. Configuraciones para comercios, edificios e industrias.</p><div className="product-specs"><span>Barral antipánico</span><span>Distintas medidas</span></div><ProductLink product="Puertas de emergencia">Cotizar puertas de emergencia</ProductLink></div></article>
            <article className="product-card"><div className="product-image accessory-image"><Image src="/images/barral-antipanico.jpg" alt="Barral antipánico modelo touch para puertas" loading="lazy" width={555} height={350}/><span className="product-tag">EL DETALLE QUE HACE LA DIFERENCIA</span><span className="product-number">03</span></div><div className="product-content"><h3>Accesorios y herrajes</h3><p>Completá tu puerta con barrales, cierrapuertas y cerraduras compatibles. Te ayudamos a elegir cada componente.</p><div className="product-specs"><span>Barrales y cerraduras</span><span>Cierrapuertas</span></div><ProductLink product="Accesorios y herrajes">Consultar por accesorios</ProductLink></div></article>
          </div>
          <div className="solutions-bottom"><p>La homologación depende del modelo y de su configuración. Consultanos por la documentación de la puerta que necesitás.</p><a href="https://www.montiukaberturas.com/assets/descargar/catalogo-montiuk-2023-alta.pdf" target="_blank" rel="noopener noreferrer" className="text-link"><svg className="icon" aria-hidden="true"><use href="#i-download"/></svg> Ver catálogo completo</a></div>
          <div className="help-banner"><div><span className="help-icon"><svg className="icon" aria-hidden="true"><use href="#i-chat"/></svg></span><p><strong>¿No sabés qué puerta necesitás?</strong> Contanos sobre tu obra. Nosotros te orientamos.</p></div><a className="text-link" href={whatsappUrl('Hola, necesito asesoramiento para elegir una puerta para mi obra.')} target="_blank" rel="noopener noreferrer">Hablar con un asesor <svg className="icon" aria-hidden="true"><use href="#i-arrow"/></svg></a></div>
        </div>
      </section>
      <section className="section why-section" id="por-que-montiuk"><div className="site-container why-grid grid grid-cols-1 min-[681px]:grid-cols-2"><div className="why-visual"><Image src="/images/puerta-cortafuego.jpg" alt="Variedad de puertas y terminaciones Montiuk" loading="lazy" width={1500} height={617}/><div className="visual-label"><span>MONTIUK / SEGURIDAD INDUSTRIAL</span><strong>Detrás de cada puerta,<br />hay un compromiso.</strong><svg className="icon" aria-hidden="true"><use href="#i-up-right"/></svg></div></div><div className="why-copy"><div className="eyebrow"><span></span> POR QUÉ ELEGIRNOS</div><h2>La tranquilidad de<br />estar bien asesorado.</h2><p className="section-intro">Sabemos que cada obra tiene sus exigencias. Por eso, te acompañamos desde la primera consulta.</p><div className="benefit"><span>01</span><div><h3>Una solución para tu proyecto</h3><p>Revisamos medidas, uso y requerimientos para orientarte hacia la puerta y los accesorios adecuados.</p></div></div><div className="benefit"><span>02</span><div><h3>Respaldo técnico, sin vueltas</h3><p>Información sobre materiales, modelos y certificaciones para que puedas decidir con confianza.</p></div></div><div className="benefit"><span>03</span><div><h3>Contacto directo y atención personal</h3><p>Conversá con nuestro equipo y coordiná tu pedido, la entrega y las necesidades de instalación.</p></div></div><a href="#contacto" className="text-link">Conversemos sobre tu obra <svg className="icon" aria-hidden="true"><use href="#i-arrow"/></svg></a></div></div></section>
      <section className="section process-section"><div className="site-container"><div className="section-heading"><div><div className="eyebrow"><span></span> SIMPLE, DE PRINCIPIO A FIN</div><h2>Tu presupuesto, en tres pasos.</h2></div><p>Acercanos tu idea. Te ayudamos a convertirla<br className="desktop-break"/> en una solución concreta.</p></div><div className="steps grid grid-cols-1 gap-[31px] min-[681px]:grid-cols-3 min-[681px]:gap-6 min-[901px]:gap-[42px]"><div className="step"><div className="step-top"><span>01</span><svg className="icon" aria-hidden="true"><use href="#i-arrow"/></svg></div><h3>Contanos qué necesitás</h3><p>Mandanos medidas, cantidad y ubicación de la obra. Si tenés un plano o una foto, sumalos al chat.</p></div><div className="step"><div className="step-top"><span>02</span><svg className="icon" aria-hidden="true"><use href="#i-arrow"/></svg></div><h3>Recibí asesoramiento y cotización</h3><p>Te orientamos sobre modelos y accesorios, y preparamos un presupuesto para tu proyecto.</p></div><div className="step"><div className="step-top"><span>03</span><svg className="icon" aria-hidden="true"><use href="#i-check"/></svg></div><h3>Coordinamos tu pedido</h3><p>Definimos juntos los detalles, los plazos y la entrega para que puedas organizar tu obra.</p></div></div></div></section>
      <section className="section faq-section" id="preguntas"><div className="site-container faq-grid"><div><div className="eyebrow"><span></span> RESOLVEMOS TUS DUDAS</div><h2>Antes de elegir,<br />hablemos claro.</h2><p>La información que necesitás<br />para dar el próximo paso.</p><a className="text-link" href="#contacto">Tengo otra consulta <svg className="icon" aria-hidden="true"><use href="#i-up-right"/></svg></a></div><div className="faq-list"><details><summary>¿Qué diferencia hay entre una puerta cortafuego y una de emergencia?<span className="faq-plus"></span></summary><p>Una puerta de emergencia facilita la salida mediante su sistema de apertura antipánico. Una puerta cortafuego, además, tiene una resistencia al fuego certificada para una configuración específica. Te ayudamos a identificar cuál corresponde según el uso y los requisitos de tu obra.</p></details><details><summary>¿Las puertas cortafuego están certificadas?<span className="faq-plus"></span></summary><p>Contamos con puertas cortafuego con homologación INTI en FR30, FR60, FR90 y FR120. La homologación depende del modelo y la configuración. Consultanos por la documentación de la puerta que necesitás.</p></details><details><summary>¿Qué datos necesitan para cotizar?<span className="faq-plus"></span></summary><p>Idealmente: tipo de puerta, medidas del vano, cantidad, localidad de entrega y resistencia al fuego requerida, si corresponde. Si todavía no tenés todos los datos, escribinos igual. Podés enviarnos fotos o planos por WhatsApp.</p></details><details><summary>¿Hacen envíos e instalación?<span className="faq-plus"></span></summary><p>Hacemos envíos a todo el país desde Buenos Aires. La instalación se cotiza por separado: consultanos la disponibilidad para tu ubicación. Coordinamos las condiciones de entrega y los plazos al preparar tu pedido.</p></details><details><summary>¿Puedo pedir una medida especial o solo accesorios?<span className="faq-plus"></span></summary><p>Sí, podés consultar por medidas especiales y comprar accesorios. En puertas cortafuego, revisamos que la configuración solicitada esté contemplada por la certificación correspondiente. Para herrajes, compartinos una foto o los datos de tu puerta para revisar compatibilidad.</p></details></div></div></section>
      <section className="section contact-section" id="contacto"><div className="site-container contact-grid"><div className="contact-copy"><div className="eyebrow light"><span></span> EMPECEMOS POR TU PROYECTO</div><h2>Una buena decisión<br />empieza con una<br /><span>conversación.</span></h2><p>Contanos qué necesitás y te ayudamos a encontrar la solución. Sin compromiso.</p><a className="contact-phone" href="tel:+541162799615">11 6279 9615 <svg className="icon" aria-hidden="true"><use href="#i-up-right"/></svg></a><a className="contact-email" href="mailto:montiuk.aberturas@gmail.com">montiuk.aberturas@gmail.com</a><div className="contact-location"><svg className="icon" aria-hidden="true"><use href="#i-pin"/></svg><span>Enrique Santamarina 923, Monte Grande<br />Buenos Aires · Envíos a todo el país</span></div></div><QuoteForm /></div></section>
    </main>
    <footer><div className="site-container"><div className="footer-main"><a className="brand" href="#inicio" aria-label="Montiuk, volver al inicio"><Image src="/images/montiuk-logo.png" width={1244} height={357} alt="Montiuk Seguridad Industrial" loading="lazy"/></a><p>Puertas que protegen.<br />Personas que te acompañan.</p><div className="footer-links"><a href="#soluciones">Soluciones</a><a href="#contacto">Contacto</a><a href="https://www.instagram.com/montiuk.aberturas/" target="_blank" rel="noopener noreferrer">Instagram <svg className="icon" aria-hidden="true"><use href="#i-up-right"/></svg></a></div></div><div className="footer-bottom"><span>© <span>{new Date().getFullYear()}</span> Montiuk Seguridad Industrial. Todos los derechos reservados.</span><span>Hecho en Argentina. Para proteger lo que importa.</span></div></div></footer>
    <a className="floating-whatsapp" href={whatsappUrl('Hola, quiero consultar por sus puertas y accesorios.')} target="_blank" rel="noopener noreferrer" aria-label="Contactar a Montiuk por WhatsApp"><svg className="icon" aria-hidden="true"><use href="#i-chat"/></svg><span>¿Te asesoramos?</span></a>
    
  
  </>;
}
